version: '2'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123
    ports:
      - 2333:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  hwk4:
    container_name: hwk5
    build: ./568_project
    image: hwk5:latest
    logging:      
      options:        
        max-size: 10m        
        max-file: "3"
    ports:
      - 12345:12345
    volumes:
      - ./568_project:/src/main/java/org/example/UpsApplication
    depends_on:
      - postgres

